### ISSUE TITLE
Faulty assertion

### ISSUE THREAD

**Issue by Stefan314** [alaatm/freecell-solver#6]
Hey, I believe there is a wrong assertion in Move.Get in line 39. I think the size check should be until 12 instead of 11. The solver runs into a lot of trouble because of this issue in deal 651717. In that deal it tries to move 12 cards, which is possible in Freecell according to this stackexchange post: https://boardgames.stackexchange.com/questions/45155/freecell-how-many-cards-can-be-moved-at-once, but it isn't in this solver because of the assertion.

**Comment by alaatm** [comment]
Hi, you're right. Thanks!
